# Ingest the data

In [8]:
import pandas as pd
import numpy as np

schema = "tables"
file_name = "wine_reviews-2026-04-11-23-44.csv"
# file_path = f"{schema}/{file_name}"
file_path = r"C:\Users\Mateusz\PycharmProjects\wines\tables\wine_reviews-2026-04-11-23-44.csv"

df = pd.read_csv(file_path, dtype=str)

print(f"Shape: {df.shape}")
df.dtypes

Shape: (135211, 22)

name               str
brand              str
company            str
vintage            str
drink_type         str
wine_type          str
varietal_label     str
alcohol            str
bottle_size        str
case_production    str
country            str
state              str
appellation        str
designation        str
retail             str
rating             str
reviewer           str
review             str
date_of_review     str
date_received      str
pub_date_web       str
slug               str
dtype: object

## Glimpse on data

In [9]:
print(f"Row count: {len(df):,}")

Row count: 135,211

In [10]:
df.head(10)

,name,brand,company,vintage,drink_type,wine_type,varietal_label,alcohol,bottle_size,case_production,...,appellation,designation,retail,rating,reviewer,review,date_of_review,date_received,pub_date_web,slug
0,ZD 2017 Founder's Reserve Pinot Noir (Carneros),ZD,ZD Wines,2017,wine,Red,Pinot Noir,0.1420,750 ml,600,...,Carneros,Founder's Reserve,90,91,V.B.,"A fruity, inviting nose of dark cherry and bak...",2019-11-01,2019-07-25,2020-03-01,zd-2017-founders-reserve-pinot-noir-carneros
1,Zaca Mesa 2017 Bien Nacido Vineyard Pinot Noir...,Zaca Mesa,Zaca Mesa Winery,2017,wine,Red,Pinot Noir,0.1410,750 ml,501,...,Santa Maria Valley,Bien Nacido Vineyard,48,93,M.K.,Broad black-cherry and macerated strawberry ar...,2019-10-01,2019-10-11,2020-09-01,zaca-mesa-2017-bien-nacido-vineyard-pinot-noir...
2,YNOT 2017 Pinot Noir (Santa Barbara County),YNOT,Flying Goat Cellars,2017,wine,Red,Pinot Noir,0.1423,750 ml,176,...,Santa Barbara County,NaN,28,92,M.K.,"Mulberry, macerated wild cherry, cherry pit an...",2020-05-02,2020-05-22,2020-10-01,ynot-2017-pinot-noir-santa-barbara-county
3,Writer's Block 2017 Pinot Noir (Lake County),Writer's Block,Steele Wines,2017,wine,Red,Pinot Noir,0.1350,750 ml,1050,...,Lake County,NaN,18,88,J.G.,"A good choice in a pleasant, well-mannered win...",2020-01-03,2019-12-14,2020-05-01,writers-block-2017-pinot-noir-lake-county
4,Work Vineyard 2017 Zina's Pinot Noir (Russian ...,Work Vineyard,Work Vineyard,2017,wine,Red,Pinot Noir,0.1470,750 ml,150,...,Russian River Valley,Zina's,55,88,V.B.,"This hearty, thick wine shows the warmth of th...",2020-07-21,2020-07-27,2020-12-01,work-vineyard-2017-zinas-pinot-noir-russian-ri...
5,Windrun 2017 No. 15 Pinot Noir (Sta. Rita Hills),Windrun,Windrun Wines,2017,wine,Red,Pinot Noir,0.1410,750 ml,350,...,Sta. Rita Hills,No. 15,33,92,M.K.,Beautifully candied dark-cherry aromas meet wi...,2020-01-18,2020-01-24,2020-05-01,windrun-2017-no-15-pinot-noir-sta-rita-hills
6,Windchaser 2017 Pinot Noir (Anderson Valley),Windchaser,Windchaser Wine Co.,2017,wine,Red,Pinot Noir,0.1330,750 ml,300,...,Anderson Valley,NaN,35,91,J.G.,Nicely ripe and well balanced at the same time...,2020-03-25,2020-03-14,2020-08-01,windchaser-2017-pinot-noir-anderson-valley
7,Willowbrook 2017 Kaufman Sunnyslope Vineyard C...,Willowbrook,Willowbrook Cellars,2017,wine,Red,Pinot Noir,0.1430,750 ml,480,...,Sonoma Mountain,Kaufman Sunnyslope Vineyard Clone 777,28,91,V.B.,"Flavors of black tea, strawberry and black che...",2020-04-02,2019-12-12,2020-09-01,willowbrook-2017-kaufman-sunnyslope-vineyard-c...
8,Wildeye 2017 Pinot Noir (Santa Lucia Highlands),Wildeye,Wildeye Winery,2017,wine,Red,Pinot Noir,0.1470,750 ml,340,...,Santa Lucia Highlands,NaN,35,88,M.K.,"Dark red plum, minty eucalyptus, wet gravel an...",2019-12-14,2019-12-17,2020-05-01,wildeye-2017-pinot-noir-santa-lucia-highlands
9,Westwood 2017 Pinot Noir (Sonoma County),Westwood,Westwood,2017,wine,Red,Pinot Noir,0.1390,750 ml,1600,...,Sonoma County,NaN,48,90,V.B.,"This is a bold, hugely concentrated wine, jamm...",2019-09-21,2019-09-26,2020-09-01,westwood-2017-pinot-noir-sonoma-county

In [11]:
df

,name,brand,company,vintage,drink_type,wine_type,varietal_label,alcohol,bottle_size,case_production,...,appellation,designation,retail,rating,reviewer,review,date_of_review,date_received,pub_date_web,slug
0,ZD 2017 Founder's Reserve Pinot Noir (Carneros),ZD,ZD Wines,2017,wine,Red,Pinot Noir,0.1420,750 ml,600,...,Carneros,Founder's Reserve,90,91,V.B.,"A fruity, inviting nose of dark cherry and bak...",2019-11-01,2019-07-25,2020-03-01,zd-2017-founders-reserve-pinot-noir-carneros
1,Zaca Mesa 2017 Bien Nacido Vineyard Pinot Noir...,Zaca Mesa,Zaca Mesa Winery,2017,wine,Red,Pinot Noir,0.1410,750 ml,501,...,Santa Maria Valley,Bien Nacido Vineyard,48,93,M.K.,Broad black-cherry and macerated strawberry ar...,2019-10-01,2019-10-11,2020-09-01,zaca-mesa-2017-bien-nacido-vineyard-pinot-noir...
2,YNOT 2017 Pinot Noir (Santa Barbara County),YNOT,Flying Goat Cellars,2017,wine,Red,Pinot Noir,0.1423,750 ml,176,...,Santa Barbara County,NaN,28,92,M.K.,"Mulberry, macerated wild cherry, cherry pit an...",2020-05-02,2020-05-22,2020-10-01,ynot-2017-pinot-noir-santa-barbara-county
3,Writer's Block 2017 Pinot Noir (Lake County),Writer's Block,Steele Wines,2017,wine,Red,Pinot Noir,0.1350,750 ml,1050,...,Lake County,NaN,18,88,J.G.,"A good choice in a pleasant, well-mannered win...",2020-01-03,2019-12-14,2020-05-01,writers-block-2017-pinot-noir-lake-county
4,Work Vineyard 2017 Zina's Pinot Noir (Russian ...,Work Vineyard,Work Vineyard,2017,wine,Red,Pinot Noir,0.1470,750 ml,150,...,Russian River Valley,Zina's,55,88,V.B.,"This hearty, thick wine shows the warmth of th...",2020-07-21,2020-07-27,2020-12-01,work-vineyard-2017-zinas-pinot-noir-russian-ri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135206,Dr. Loosen 1993 Tradition Ürziger Würzgarten S...,Dr. Loosen,Loosen Bros. USA,1993,wine,White,Riesling,0.0750,750 ml,111,...,Mosel,Tradition Ürziger Würzgarten Spätlese,109,92,A.Z.,A beautifully mature wine that wears its age w...,2025-10-30,2025-10-06,2026-02-01,dr-loosen-1993-tradition-urziger-wurzgarten-sp...
135207,Presidential NV 40 Years Old Tawny Port (Port),Presidential,"Jack Poust & Company, Inc.",NV,wine,Port,Port,0.2000,750 ml,150,...,Port,40 Years Old Tawny,120,91,R.V.,An old gold aroma comes from this wood-aged Po...,2025-12-29,2025-12-29,2026-04-01,presidential-nv-40-years-old-tawny-port-port
135208,Fonseca NV 10 Year Old Tawny Port (Port),Fonseca,Kobrand,NV,wine,Port,Port,0.2000,750 ml,2400,...,Port,10 Year Old Tawny,43,91,R.V.,There is an attractive flash of wood aging in ...,2025-11-29,2025-11-26,2026-04-01,fonseca-nv-10-year-old-tawny-port-port
135209,Domeniile Averesti NV Nativus Sauvignon Blanc ...,Domeniile Averesti,Domeniile Averesti,NV,wine,White,Sauvignon Blanc,0.1400,750 ml,8000,...,Huşi,Nativus,35,91,R.S.,Bread dough and toasty-pastry aromas open on t...,2025-09-27,2025-07-18,2026-04-01,domeniile-averesti-nv-nativus-sauvignon-blanc-...
135210,Domeniile Averesti NV Diamond Selection Busuio...,Domeniile Averesti,Domeniile Averesti,NV,wine,Rose,Busuioaca de Bohotin,0.1300,750 ml,2000,...,Huşi,Diamond Selection,45,91,R.S.,This wine has an enticing floral-first nose th...,2025-09-27,2025-07-18,2026-04-01,domeniile-averesti-nv-diamond-selection-busuio...

## Save as Parquet (Bronze)

In [12]:
df.to_parquet("tables/wine_reviews_bronze.parquet", index=False)
print("Bronze parquet written.")

OSError: Cannot save file into a non-existent directory: 'tables'

# Cleaning and casting

## Casting column types

In [13]:
cast_columns = [
    ("alcohol",         "float"),
    ("vintage",         "int"),
    ("case_production", "int"),
    ("retail",          "float"),
    ("rating",          "int"),
    ("bottle_size",     "float"),
]

df_cast = df.copy()

for column, dtype in cast_columns:
    nulls_before = df_cast[column].isna().sum()
    cast_col = pd.to_numeric(df_cast[column], errors="coerce")
    nulls_after = cast_col.isna().sum()
    error_mask = df_cast[column].notna() & cast_col.isna()
    failures = error_mask.sum()

    df_cast[f"{column}_cast"] = cast_col
    df_cast[f"{column}_error"] = df_cast[column].where(error_mask)

    print(f"{column:20s}  nulls before={nulls_before:>6,}  after={nulls_after:>6,}  failures={failures:>6,}")
    if failures > 0:
        print(df_cast.loc[error_mask, column].unique())

alcohol               nulls before=     0  after=     0  failures=     0
vintage               nulls before=     0  after= 4,619  failures= 4,619
<ArrowStringArray>
['NV']
Length: 1, dtype: str
case_production       nulls before=     0  after=     0  failures=     0
retail                nulls before=     0  after=     0  failures=     0
rating                nulls before=     0  after=     0  failures=     0
bottle_size           nulls before=     0  after=129,468  failures=129,468
<ArrowStringArray>
[  '750 ml',    '1.5 L',      '3 L',   '375 ml',   '250 ml',   '500 ml',
      '1 L',   '620 ml',   '187 ml',   '200 ml',  '3000 ml', '1.5 L ml',
   '3 L ml',   '751 ml',    '75 ml',  '7502 ml',  '7500 ml',   '075 ml',
     '1 ml',  '4000 ml',  '0750 ml',  '1500 ml', '30000 ml',  '7505 ml',
   '749 ml',  '7508 ml',     '2 ml',     '7 ml',   '150 ml', '20000 ml',
   '650 ml',   '450 ml',   '330 ml',   '100 ml',  '2729 ml',    '15 ml',
   '1 L ml',  '1000 ml',   '740 ml',   '700 ml',     '0 ml']
Length: 41, dtype: str

In [14]:
df_cast.dtypes

name                         str
brand                        str
company                      str
vintage                      str
drink_type                   str
wine_type                    str
varietal_label               str
alcohol                      str
bottle_size                  str
case_production              str
country                      str
state                        str
appellation                  str
designation                  str
retail                       str
rating                       str
reviewer                     str
review                       str
date_of_review               str
date_received                str
pub_date_web                 str
slug                         str
alcohol_cast             float64
alcohol_error                str
vintage_cast             float64
vintage_error                str
case_production_cast       int64
case_production_error        str
retail_cast              float64
retail_error                 str
rating_cast                int64
rating_error                 str
bottle_size_cast         float64
bottle_size_error            str
dtype: object

## Special cleaning and feature creation

### alcohol

In [15]:
df_cast["alcohol_cast"].value_counts(dropna=False).head(1000)

alcohol_cast
0.1350    19629
0.1450    18536
0.1300    17267
0.1400    15769
0.1250    11931
          ...
0.0142        1
0.0130        1
0.0940        1
0.1960        1
0.0810        1
Name: count, Length: 448, dtype: int64

In [16]:
df_cast["alcohol_cast"].value_counts(dropna=False).sort_index(ascending=False).head(1000)

alcohol_cast
 267.000       1
 54.800        1
 50.000        1
 20.190        1
 16.000        1
            ...
 0.005         6
 0.000      1463
-0.010        10
-0.020        11
-2.000         1
Name: count, Length: 448, dtype: int64

In [ ]:
def fix_alcohol(v):
    if pd.isna(v):
        return np.nan
    if v > 25.0:
        return np.nan
    if v > 7.0:
        return v / 100
    if v > 2.5:
        return np.nan
    if v > 0.7:
        return v / 10
    if v > 0.25:
        return np.nan
    if v >= 0.05:
        return v
    return np.nan

df_cast["alcohol"] = df_cast["alcohol_cast"].map(fix_alcohol)

In [17]:
df_cast["alcohol"].value_counts(dropna=False).head(1000)

alcohol
0.1350    19629
0.1450    18536
0.1300    17267
0.1400    15769
0.1250    11931
          ...
0.0142        1
0.0130        1
0.0940        1
0.1960        1
0.0810        1
Name: count, Length: 448, dtype: int64

### vintage

In [18]:
df_cast["vintage_cast"].nunique()

56

In [19]:
df_cast["vintage_cast"].value_counts(dropna=False).head(1000)

vintage_cast
2019.0    22232
2018.0    20294
2021.0    18996
2020.0    17544
2022.0    15820
2017.0    12222
2023.0     9450
2016.0     5907
NaN        4619
2024.0     3320
2015.0     2529
2014.0      777
2013.0      490
2012.0      296
2011.0      150
2010.0      125
2009.0      103
2008.0       69
2025.0       52
2007.0       41
2004.0       27
2005.0       25
2006.0       24
2000.0       12
2001.0        8
2003.0        8
1999.0        8
2002.0        7
1995.0        5
1997.0        4
1998.0        4
1990.0        4
1991.0        4
1996.0        3
1989.0        2
1980.0        2
1976.0        2
1975.0        2
1983.0        2
1994.0        2
1978.0        2
1962.0        2
1974.0        2
1981.0        1
1969.0        1
1977.0        1
1992.0        1
1967.0        1
1961.0        1
1982.0        1
1972.0        1
1988.0        1
1987.0        1
1985.0        1
1986.0        1
1965.0        1
1993.0        1
Name: count, dtype: int64

In [20]:
df_cast["is_nv"] = (df_cast["vintage_error"] == "NV").astype(int)
df_cast["is_nv"].value_counts()

is_nv
0    130592
1      4619
Name: count, dtype: int64

### case_production

In [21]:
df_cast["case_production_cast"].nunique()

6354

In [22]:
df_cast["case_production_cast"].value_counts(dropna=False).head(10000)

case_production_cast
0           39114
1000         2385
500          2375
2000         2261
5000         2243
            ...
309000          1
15000000        1
6554            1
8255            1
12209           1
Name: count, Length: 6354, dtype: int64

### retail

In [23]:
df_cast["retail_cast"].value_counts(dropna=False).head(1000)

retail_cast
0.00      8035
20.00     6882
25.00     6388
30.00     5677
15.00     5105
          ...
207.00       1
1.00         1
49.99        1
424.00       1
26.90        1
Name: count, Length: 491, dtype: int64

In [24]:
df_cast["retail"] = df_cast["retail_cast"].replace(0.0, np.nan)

### rating

In [25]:
df_cast["rating_cast"].value_counts(dropna=False).head(1000)

rating_cast
90     21741
91     17712
92     17169
88     15746
89     13984
93     13498
87      9543
94      8405
86      5117
95      4052
85      2679
96      1965
84      1264
97       923
83       522
98       377
82       253
99        92
81        56
80        54
100       49
44         5
22         5
Name: count, dtype: int64

In [26]:
df_cast["rating_cast"].value_counts(dropna=False).sort_index(ascending=False).head(1000)

rating_cast
100       49
99        92
98       377
97       923
96      1965
95      4052
94      8405
93     13498
92     17169
91     17712
90     21741
89     13984
88     15746
87      9543
86      5117
85      2679
84      1264
83       522
82       253
81        56
80        54
44         5
22         5
Name: count, dtype: int64

In [27]:
df_cast["rating"] = df_cast["rating_cast"].replace(0, np.nan)

### bottle_size

In [28]:
df_cast["bottle_size"].value_counts(dropna=False).head(1000)

bottle_size
750 ml      128326
750           5721
375 ml         447
500 ml         160
75 ml           90
1.5 L           84
250 ml          83
3 L             78
1 L             78
075 ml          48
3000 ml         12
375             12
187 ml          11
500              6
1.5 L ml         5
100 ml           5
1500 ml          4
620 ml           3
7500 ml          3
0750 ml          3
3 L ml           2
250              2
751 ml           2
2 ml             2
740 ml           2
200 ml           1
0750             1
0                1
7502 ml          1
1 ml             1
4000 ml          1
30000 ml         1
7505 ml          1
749 ml           1
7508 ml          1
7 ml             1
150 ml           1
20000 ml         1
650 ml           1
450 ml           1
330 ml           1
2729 ml          1
15 ml            1
1 L ml           1
1000 ml          1
700 ml           1
0 ml             1
Name: count, dtype: int64

In [29]:
def parse_bottle_size(s):
    if pd.isna(s):
        return np.nan
    s = str(s).strip()
    s_lower = s.lower()
    if s_lower.endswith("l ml"):
        try:
            return float(s[:-4].strip()) * 1000
        except ValueError:
            return np.nan
    elif s_lower.endswith("ml"):
        try:
            return float(s[:-2].strip())
        except ValueError:
            return np.nan
    elif s_lower.endswith("l"):
        try:
            return float(s[:-1].strip()) * 1000
        except ValueError:
            return np.nan
    else:
        try:
            return float(s)
        except ValueError:
            return np.nan

df_cast["bottle_size"] = df_cast["bottle_size"].map(parse_bottle_size)

In [30]:
valid_sizes = {750.0, 375.0, 500.0, 1500.0, 3000.0, 250.0, 1000.0, 187.0, 620.0}

def clean_bottle_size(v):
    if pd.isna(v):
        return np.nan
    if v == 75.0:
        return 750.0
    if v == 751.0:
        return 750.0
    if v == 740.0:
        return 750.0
    if v in valid_sizes:
        return v
    return np.nan

df_cast["bottle_size"] = df_cast["bottle_size"].map(clean_bottle_size)

In [31]:
df_cast["bottle_size"].value_counts(dropna=False).head(1000)

bottle_size
750.0     134193
375.0        459
500.0        166
1500.0        93
3000.0        92
250.0         85
1000.0        80
NaN           29
187.0         11
620.0          3
Name: count, dtype: int64

## Summary of nulls

In [32]:
null_counts = df_cast[df.columns].isnull().sum()

print(f"{'column':<25}  {'nulls':>8}")
print("-" * 37)
for c, n in null_counts.items():
    print(f"{c:<25}  {n:>8,}")

column                        nulls
-------------------------------------
name                              0
brand                             0
company                           2
vintage                           0
drink_type                        0
wine_type                         0
varietal_label                   12
alcohol                           0
bottle_size                      29
case_production                   0
country                           0
state                             0
appellation                       0
designation                  32,421
retail                        8,035
rating                            0
reviewer                        244
review                           17
date_of_review                    0
date_received                     0
pub_date_web                      0
slug                              0

In [33]:
df_cast

,name,brand,company,vintage,drink_type,wine_type,varietal_label,alcohol,bottle_size,case_production,...,vintage_error,case_production_cast,case_production_error,retail_cast,retail_error,rating_cast,rating_error,bottle_size_cast,bottle_size_error,is_nv
0,ZD 2017 Founder's Reserve Pinot Noir (Carneros),ZD,ZD Wines,2017,wine,Red,Pinot Noir,0.1420,750.0,600,...,NaN,600,NaN,90.0,NaN,91,NaN,NaN,750 ml,0
1,Zaca Mesa 2017 Bien Nacido Vineyard Pinot Noir...,Zaca Mesa,Zaca Mesa Winery,2017,wine,Red,Pinot Noir,0.1410,750.0,501,...,NaN,501,NaN,48.0,NaN,93,NaN,NaN,750 ml,0
2,YNOT 2017 Pinot Noir (Santa Barbara County),YNOT,Flying Goat Cellars,2017,wine,Red,Pinot Noir,0.1423,750.0,176,...,NaN,176,NaN,28.0,NaN,92,NaN,NaN,750 ml,0
3,Writer's Block 2017 Pinot Noir (Lake County),Writer's Block,Steele Wines,2017,wine,Red,Pinot Noir,0.1350,750.0,1050,...,NaN,1050,NaN,18.0,NaN,88,NaN,NaN,750 ml,0
4,Work Vineyard 2017 Zina's Pinot Noir (Russian ...,Work Vineyard,Work Vineyard,2017,wine,Red,Pinot Noir,0.1470,750.0,150,...,NaN,150,NaN,55.0,NaN,88,NaN,NaN,750 ml,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135206,Dr. Loosen 1993 Tradition Ürziger Würzgarten S...,Dr. Loosen,Loosen Bros. USA,1993,wine,White,Riesling,0.0750,750.0,111,...,NaN,111,NaN,109.0,NaN,92,NaN,NaN,750 ml,0
135207,Presidential NV 40 Years Old Tawny Port (Port),Presidential,"Jack Poust & Company, Inc.",NV,wine,Port,Port,0.2000,750.0,150,...,NV,150,NaN,120.0,NaN,91,NaN,NaN,750 ml,1
135208,Fonseca NV 10 Year Old Tawny Port (Port),Fonseca,Kobrand,NV,wine,Port,Port,0.2000,750.0,2400,...,NV,2400,NaN,43.0,NaN,91,NaN,NaN,750 ml,1
135209,Domeniile Averesti NV Nativus Sauvignon Blanc ...,Domeniile Averesti,Domeniile Averesti,NV,wine,White,Sauvignon Blanc,0.1400,750.0,8000,...,NV,8000,NaN,35.0,NaN,91,NaN,NaN,750 ml,1
135210,Domeniile Averesti NV Diamond Selection Busuio...,Domeniile Averesti,Domeniile Averesti,NV,wine,Rose,Busuioaca de Bohotin,0.1300,750.0,2000,...,NV,2000,NaN,45.0,NaN,91,NaN,NaN,750 ml,1